# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWin(object):
    def setupUi(self, RegisterWin):
        RegisterWin.setObjectName("RegisterWin")
        RegisterWin.resize(772, 439)
        self.label = QtWidgets.QLabel(RegisterWin)
        self.label.setGeometry(QtCore.QRect(40, 40, 662, 341))
        self.label.setMinimumSize(QtCore.QSize(501, 0))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(RegisterWin)
        self.label_2.setGeometry(QtCore.QRect(150, 140, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(RegisterWin)
        self.label_3.setGeometry(QtCore.QRect(150, 240, 72, 15))
        self.label_3.setObjectName("label_3")
        self.re_user = QtWidgets.QLineEdit(RegisterWin)
        self.re_user.setGeometry(QtCore.QRect(320, 140, 211, 21))

        self.re_user.setObjectName("re_user")
        self.re_passwd = QtWidgets.QLineEdit(RegisterWin)
        self.re_passwd.setGeometry(QtCore.QRect(320, 230, 211, 21))

        self.re_passwd.setObjectName("re_passwd")
        self.yes = QtWidgets.QPushButton(RegisterWin)
        self.yes.setGeometry(QtCore.QRect(150, 320, 93, 28))

        self.yes.setObjectName("yes")
        self.back = QtWidgets.QPushButton(RegisterWin)
        self.back.setGeometry(QtCore.QRect(460, 320, 93, 28))
        self.back.setObjectName("back")

        self.retranslateUi(RegisterWin)
        QtCore.QMetaObject.connectSlotsByName(RegisterWin)

    def retranslateUi(self, RegisterWin):
        _translate = QtCore.QCoreApplication.translate
        RegisterWin.setWindowTitle(_translate("RegisterWin", "Form"))
        self.label_2.setText(_translate("RegisterWin", "注册用户"))
        self.label_3.setText(_translate("RegisterWin", "输入密码"))
        self.yes.setText(_translate("RegisterWin", "确定"))
        self.back.setText(_translate("RegisterWin", "返回"))
